### ISSUE TITLE
kleinigchkeit Antwortmöglichkeiten main/pua/content/jupyterquiz/quiz_listen.ipynb q4

### ISSUE THREAD

**Issue by Falkenberg-Marc** [tferber/jupyterbooks#1]
Die Antwortmöglichkeiten in https://github.com/tferber/jupyterbooks/blob/main/pua/content/jupyterquiz/quiz_listen.ipynb q4 sind eine mischung aus den möglichen antworten der formen  b = [1,5,3] oder b[1]=5 oder der ausgabe 5, welche einzeln im selben style wie die anderne fragen wären.

**Comment by tferber** [comment]
Thanks, fixed!
